### PR TITLE
Add go.mod and go.sum

### PR DESCRIPTION
**Pull request by iwat**
This should be easy except that github.com/cheggaaa/pb breaks Go [module practices](https://github.com/golang/go/wiki/Modules#semantic-import-versioning) by hosting v2 on the same path which caused a confusion on "go mod" command. Therefore, go.mod is needed and must explicitly define that it needs `github.com/cheggaaa/pb 1.0.27` otherwise it will choose v2.x.x which is not compatible.

### CODE REVIEW

**Comment by iwat** [comment]
Build failed
```
dyndump/s3deleter_test.go:57: Sprintf call has arguments but no formatting directives
```
Unrelated to my change.

**Comment by gwatts** [comment]
Thanks for the PR; overdue to add module support... I made an import update instead to address the pb issue - Take a look at #5 and checkout the `add_go_mod` branch and see if it works for you; I'll merge that one down to master if so

**Comment by iwat** [comment]
That branch works great, merge please.

**Comment by gwatts** [comment]
Thanks for validating - Merged; closing this PR as it's duplicated by #5

**Pull request closed without merging**
